### ISSUE TITLE
Lots of Python errors

### ISSUE THREAD

**Issue by Firebolt9907** [jaydenmilne/steamsync#24]
[crash.txt](https://github.com/jaydenmilne/steamsync/files/8011327/crash.txt)

**Comment by jaydenmilne** [comment]
```
steamsync v0.3.0 -  Encountered An Error. Please submit a bug report at https://github.com/jaydenmilne/steamsync/issues with this log!
Traceback (most recent call last):

  File "main.py", line 63, in next

  File "main.py", line 228, in __init__

  File "steamsync.py", line 106, in egs_collect_games

  File "json\__init__.py", line 293, in load

  File "json\__init__.py", line 346, in loads

  File "json\decoder.py", line 337, in decode

  File "json\decoder.py", line 353, in raw_decode

json.decoder.JSONDecodeError: Invalid \escape: line 7 column 25 (char 204)


Log:

steampath C:\Program Files (x86)\Steam
manifestPath C:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests
Scanning EGS manifest store (C:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests)...
Exception!!!

```
