### ISSUE TITLE
Unable to download art

### ISSUE THREAD

**Issue by Roxoriku** [jaydenmilne/steamsync#34]
When using the --download-art-all-shortcuts options it returns the following:

> Traceback (most recent call last):
  File "C:\Users\LaneT\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\LaneT\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\LaneT\AppData\Local\Programs\Python\Python310\Scripts\steamsync.exe\__main__.py", line 7, in <module>
  File "C:\Users\LaneT\AppData\Local\Programs\Python\Python310\lib\site-packages\steamsync\steamsync.py", line 643, in main
    result, msg = add_games_to_shortcut_file(
  File "C:\Users\LaneT\AppData\Local\Programs\Python\Python310\lib\site-packages\steamsync\steamsync.py", line 346, in add_games_to_shortcut_file
    success = steamdb.download_art(user, game, should_replace_existing=False)
  File "C:\Users\LaneT\AppData\Local\Programs\Python\Python310\lib\site-packages\steamsync\steameditor.py", line 280, in download_art
    targets = self._get_grid_art_destinations(game, user)
  File "C:\Users\LaneT\AppData\Local\Programs\Python\Python310\lib\site-packages\steamsync\steameditor.py", line 384, in _get_grid_art_destinations
    shortcut = self._get_steam_shortcut_id(exe, game.display_name)
  File "C:\Users\LaneT\AppData\Local\Programs\Python\Python310\lib\site-packages\steamsync\steameditor.py", line 373, in _get_steam_shortcut_id
    unique_id = "".join([exe, appname])
TypeError: sequence item 1: expected str instance, NoneType found

And no art is added to the shortcut, of course.

**Comment by madkoding** [comment]
Same here

```
Downloading art for existing shortcuts...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Scripts\steamsync.exe\__main__.py", line 7, in <module>
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\steamsync\steamsync.py", line 643, in main
    result, msg = add_games_to_shortcut_file(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\steamsync\steamsync.py", line 346, in add_games_to_shortcut_file
    success = steamdb.download_art(user, game, should_replace_existing=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\steamsync\steameditor.py", line 280, in download_art
    targets = self._get_grid_art_destinations(game, user)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\steamsync\steameditor.py", line 384, in _get_grid_art_destinations
    shortcut = self._get_steam_shortcut_id(exe, game.display_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\steamsync\steameditor.py", line 373, in _get_steam_shortcut_id
    unique_id = "".join([exe, appname])
                ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 1: expected str instance, NoneType found
```

**Comment by jaydenmilne** [comment]
Try steamsync 0.4.2

**Comment by electricsteve** [comment]
I am using 0.4.2 and it still happens.
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\elect\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\steamsync.exe\__main__.py", line 7, in <module>
  File "C:\Users\elect\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\steamsync\steamsync.py", line 652, in main
    result, msg = add_games_to_shortcut_file(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elect\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\steamsync\steamsync.py", line 390, in add_games_to_shortcut_file
    f"Replacing {old_shortcut['appname']} ({get_exe_from_shortcut(old_shortcut)} {old_shortcut.get('LaunchOptions', '')})\n     with {new_shortcut['appname']} ({get_exe_from_shortcut(new_shortcut)} {new_shortcut.get('LaunchOptions', '')})"
                 ~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'appname'
```

**Comment by electricsteve** [comment]
Looks like it's a problem with replacing
